import { useRouter } from 'next/router';
import CourseShell from '../components/course/CourseShell';

const moduleInfo = {"title":["Chocolatería","Chocolate Work"],"q":["¿Qué cambia cuando controlamos la cristalización del chocolate?","What changes when we control chocolate crystallization?"],"result":["Reconstruir la secuencia documentada del temperado y aplicarla al análisis de piezas moldeadas, rellenas y decorativas, comparando las operaciones de cada preparación.","Reconstruct the documented tempering sequence and apply it to the analysis of molded, filled, and decorative pieces, comparing the operations in each preparation."],"lessons":[["51","El chocolate como materia prima","Reconoce los tipos de chocolate que aparecen en la fuente y qué cambia al trabajar con esta materia prima.","Recognize the types of chocolate in the source and what changes when working with this ingredient.","/leccion-chocolate-como-materia-prima"],["52","Temperado: controlar la cristalización","Comprende la secuencia del temperado y su relación con el trabajo del chocolate.","Understand the tempering sequence and its relationship to working with chocolate.","/leccion-temperado-cristalizacion"],["53","Chocolate moldeado","Relaciona el chocolate temperado con moldes y piezas moldeadas documentadas.","Relate tempered chocolate to the documented molds and molded pieces.","/leccion-chocolate-moldeado"],["54","Rellenos y ganaches","Observa cómo el chocolate pasa de cobertura o pieza a preparación para relleno.","Observe how chocolate moves from coating or piece to a filling preparation.","/leccion-rellenos-y-ganaches"],["55","Bombonería, trufas, rochers y cortes","Distingue diferentes formas de trabajar, porcionar y terminar preparaciones de chocolate documentadas.","Distinguish different ways of working, portioning, and finishing documented chocolate preparations.","/leccion-bomboneria-trufas-rochers-cortes"],["56","Transfer y acabado","Reconoce el uso del transfer y otras operaciones de acabado documentadas en la fuente.","Recognize the use of transfer sheets and other finishing operations documented in the source.","/leccion-transfer-y-acabado"],["57","Ganaches avanzadas: trimolina, sorbitol y emulsión","Integra los ingredientes y operaciones específicos de las ganaches avanzadas que aparecen en la fuente.","Integrate the specific ingredients and operations of the advanced ganaches in the source.","/leccion-ganaches-avanzadas"],["58","Petit fours frescos: café y mango","Clase 23 · Reconstruye Delicias de café y Bocadito de Mango a partir de sus componentes, temperaturas y secuencias documentadas.","Class 23 · Reconstruct Delicias de café and Bocadito de Mango from their documented components, temperatures, and sequences.","/leccion-petit-fours-frescos"]]};

export default function Module7Page() {
  const { locale = 'es' } = useRouter();
  const en = locale === 'en';
  const t = {
    title: moduleInfo.title[en ? 1 : 0],
    question: moduleInfo.q[en ? 1 : 0],
    result: moduleInfo.result[en ? 1 : 0],
    next: ["Hasta ahora el curso ha trabajado masas, fermentación y laminados. En este módulo el foco cambia a una materia prima que exige controlar su estado antes de convertirla en piezas, rellenos o acabados.","So far the course has worked with doughs, fermentation, and laminated doughs. This module shifts to a raw material whose state must be controlled before it becomes pieces, fillings, or finishes."][en ? 1 : 0],
    study: ["Empieza por reconocer la cobertura. Después reconstruye el temperado, sigue una preparación documentada, observa cómo cambian las operaciones cuando aparece un molde, un relleno o un acabado y explica la secuencia con evidencia de la receta.","Start by recognizing the couverture. Then reconstruct tempering, follow a documented preparation, observe how operations change when a mold, filling, or finish appears, and explain the sequence using evidence from the recipe."][en ? 1 : 0],
    integration: ["Elige una preparación de chocolate documentada y reconstruye su recorrido: tipo de cobertura, temperado, operación principal, enfriado y acabado. Después compárala con otra preparación y señala qué operaciones permanecen y cuáles cambian.","Choose a documented chocolate preparation and reconstruct its path: couverture type, tempering, main operation, cooling, and finishing. Then compare it with another preparation and identify which operations remain and which change."][en ? 1 : 0],
  };
  const lessons = moduleInfo.lessons.map(([number, title, es, english, href]) => [number, en ? english : title, en ? english : es, href]);

  return (
    <CourseShell eyebrow={en ? 'Module 7' : 'Módulo 7'} title={t.title} backHref={en ? '/en/ruta' : '/ruta'} backLabel={en ? 'Back to course' : 'Volver a la ruta'}>
      <div className="space-y-8">
        <div className="grid gap-4 md:grid-cols-2">
          <section className="rounded-2xl border border-stone-200 bg-white p-6"><p className="text-sm font-medium text-stone-500">{en ? 'Guiding question' : 'Pregunta guía'}</p><p className="mt-3 text-lg leading-8 text-stone-800">{t.question}</p></section>
          <section className="rounded-2xl border border-stone-200 bg-white p-6"><p className="text-sm font-medium text-stone-500">{en ? 'By the end' : 'Al terminar'}</p><p className="mt-3 leading-7 text-stone-700">{t.result}</p></section>
        </div>
        <section className="rounded-2xl bg-amber-50 p-6"><p className="text-sm font-medium text-amber-900">{en ? 'The next change' : 'El siguiente cambio'}</p><p className="mt-2 max-w-3xl leading-7 text-amber-950">{t.next}</p></section>
        <section className="rounded-2xl border border-stone-200 bg-white p-6 sm:p-8"><p className="text-sm font-medium uppercase tracking-[0.14em] text-amber-700">{en ? 'How to study this module' : 'Cómo estudiar este módulo'}</p><h2 className="mt-2 text-2xl font-semibold text-stone-900">{en ? 'Understand → Do → Observe → Explain' : 'Comprende → Haz → Observa → Explica'}</h2><p className="mt-3 max-w-3xl leading-7 text-stone-700">{t.study}</p><div className="mt-5 grid gap-3 md:grid-cols-4">{(en ? [['1. Understand','Identify the stage, objective, or component.'],['2. Do','Follow the documented sequence.'],['3. Observe','Record visible signals, consistency, temperature, or structure.'],['4. Explain','Relate the signal to the operation.']] : [['1. Comprende','Identifica la etapa, objetivo o componente.'],['2. Haz','Sigue la secuencia documentada.'],['3. Observa','Registra señales visibles, consistencia, temperatura o estructura.'],['4. Explica','Relaciona la señal con la operación.']]).map(([a,b]) => <div key={a}><p className="font-semibold text-stone-900">{a}</p><p className="mt-1 text-sm leading-6 text-stone-600">{b}</p></div>)}</div></section>
        <section><div className="mb-4 flex items-end justify-between gap-4"><div><p className="text-sm font-medium uppercase tracking-[0.14em] text-amber-700">{en ? 'Learning path' : 'Ruta de aprendizaje'}</p><h2 className="mt-1 text-2xl font-semibold text-stone-900">{en ? 'Lessons' : 'Lecciones'}</h2></div><span className="text-sm text-stone-500">{lessons.length} {en ? 'lessons' : 'lecciones'}</span></div><div className="grid gap-3">{lessons.map(([number,title,description,href]) => <a key={number} href={(en ? '/en' : '') + href} className="flex items-center gap-4 rounded-2xl border border-amber-300 bg-white p-5 shadow-sm transition hover:border-amber-500 hover:shadow-md"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-amber-100 text-sm font-semibold text-amber-900">{number}</span><span className="min-w-0 flex-1"><span className="block font-semibold text-stone-900">{title}</span><span className="mt-1 block text-sm leading-6 text-stone-600">{description}</span></span><span className="shrink-0 text-sm font-medium text-amber-800">{en ? 'Open lesson →' : 'Abrir lección →'}</span></a>)}</div></section>
        <section className="rounded-2xl border border-amber-200 bg-amber-50 p-6 sm:p-8"><p className="text-sm font-medium text-amber-900">{en ? 'Module integration' : 'Integración del módulo'}</p><h2 className="mt-2 text-2xl font-semibold text-amber-950">{en ? 'Classify → reconstruct → explain' : 'Clasifica → reconstruye → explica'}</h2><p className="mt-3 max-w-3xl leading-7 text-amber-950">{t.integration}</p></section>
      </div>
    </CourseShell>
  );
}
